
# html lang
language: zh-Hans

# main menu navigation
menu:
  home: /
  search: /search
  about: /about

# stylesheets loaded in the <head>
stylesheets:
# - /css/normalize.css
- //cdn.bootcss.com/pure/1.0.0/pure-min.css
- /css/microb.css

# scripts loaded in the end of the body
scripts:
#- //cdn.bootcss.com/zepto/1.2.0/zepto.min.js
#- /js/microb.js

# switch
show_excerpt: true
show_date: true